### PR TITLE
Tests For `numerics/functions`

### PR DESCRIPTION
**Pull request by bkc39**
This pull request is to address #20.

### CODE REVIEW

**Comment by bkc39** [comment]
Check the Travis. Something is screwed up with our project config. The tests all pass:

``` bash
(λ  bkc39 . racket/mechanics) (λ b . numerics/functions-test) λ raco test .
raco test: "./info.rkt"
raco test: @(test-responsible '(ben ben))
raco test: (submod "./main.rkt" test)
raco test: @(test-responsible '(ben ben))
raco test: (submod "./private/kernel/interval.rkt" test)
raco test: @(test-responsible '(ben ben))
raco test: "./private/kernel/numbers.rkt"
raco test: @(test-responsible '(ben ben))
raco test: (submod "./private/kernel/vector.rkt" test)
raco test: @(test-responsible '(ben ben))
raco test: (submod "./private/numerics/functions/bessel.rkt" test)
raco test: @(test-responsible '(ben ben))
4 success(es) 0 failure(s) 0 error(s) 4 test(s) run
0

^Cuser break
```

But the race command hangs. Same thing happens with `raco pkg update`. The cover command also fails:

``` bash
(λ  bkc39 . numerics/functions) (λ b . numerics/functions-test) λ raco cover .
generating test coverage for ("/Users/bkc39/Documents/cs/racket/mechanics/private/numerics/functions/bessel.rkt" "/Users/bkc39/Documents/cs/racket/mechanics/private/numerics/functions/bessjs.rkt" "/Users/bkc39/Documents/cs/racket/mechanics/private/numerics/functions/elliptic-flo.rkt" "/Users/bkc39/Documents/cs/racket/mechanics/private/numerics/functions/elliptic.rkt")
Seg fault (internal error) at 0x7fff5f3ffff8
[1]    12047 segmentation fault  raco cover .
```

What version of Racket are you using?

**Comment by bennn** [comment]
Oooh this is exciting!

On Racket 6.3 (current head, updated last night) things work GREAT and the whole package compiles for me in 10 seconds.

On Racket 6.2, it takes 5 minutes to segfault.

On Racket 6.1, things are great again.

The plot thickens!!!
(You should upgrade to a git install.)

**Comment by bkc39** [comment]
God damn it. I'll up to `HEAD` on Racket. Tell someone in your lab to fix this tho. Very annoying.

**Comment by bennn** [comment]
It's definitely a problem in bessjs, in the test submodule.

**Comment by bennn** [comment]
Here's the minimal example. It's not our problem!

```
#lang racket/base

(module+ siggy
  (require (only-in math/matrix vector*->matrix))
  (vector*->matrix '#()))
```

Submitted here:
https://github.com/racket/math/issues/4

**Comment by bennn** [comment]
Anyway, looks good to merge

**Comment by bkc39** [comment]
Merged

**Pull request merged**
