### PR TITLE
Cmdline

### PR DESCRIPTION
**Pull request by bennn**
Outline a command-line interface.
- `racket main.rkt` starts a repl
- `raco mechanics` does the same thing.

This repl loads `bessel.rkt`. Otherwise it's a pretty normal racket [xrepl](http://docs.racket-lang.org/xrepl/index.html?q=xrepl)

Also
- Calling `(require mechanics/numerics)` imports things from `numerics/functions`. This interface should eventually export all of the numerics lib.
- Typing `'SICM` in the repl prints a banner

### CODE REVIEW

**Comment by bkc39** [comment]
The banner is illegible:

screen shot 2015-10-10 at 1 18 49 pm

Also this seems to have broken the build for some reason.

screen shot 2015-10-10 at 1 21 19 pm

**Comment by bkc39** [comment]
TODO before merge:
- [ ] Fix the banner
- [x] Debug the build

**Comment by bennn** [comment]
The banner is just to demonstrate how we could plug in a custom equation printer later on. If you don't want the ascii art, I'll just remove it.

The build passes on 6.3, right? I think that segfault is the same `vector*->matrix` issue.

**Comment by bkc39** [comment]
Yes. Bug is from the `vector*->matrix`. 

I'm not opposed to the ascii art. I'm just saying if we have it, just make it something readable rather than a cacophony of semicolons.

**Comment by bennn** [comment]
Here's a smaller Newton (80 chars)
screen shot 2015-10-11 at 8 05 56 pm

**Comment by bkc39** [comment]
Yea, looks much better. I say do it to it and merge this thing.

**Pull request merged**
